services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - superset-network

  superset:
    build: .
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: your-secret-key
      SUPERSET_DATABASE_HOST: postgres
      SUPERSET_DATABASE_USER: superset
      SUPERSET_DATABASE_PASSWORD: superset
      SUPERSET_DATABASE_DB: superset
    depends_on:
      - postgres
    networks:
      - superset-network

volumes:
  postgres_data:

networks:
  superset-network: